// BLOG SYSTEM: Portable schema reference for the future production database.
// The current implementation uses a typed JSON store with the same table shape.
export const blogDatabaseSchema = {
  users: {
    id: "string primary key",
    name: "string",
    email: "string unique",
    password: "string hashed_password_in_production",
    role: "admin | author",
    createdAt: "datetime",
  },
  blogs: {
    id: "string primary key",
    title: "string",
    slug: "string unique seo_url",
    featuredImage: "string optional_empty_for_text_only",
    imageAlt: "string",
    shortDescription: "text",
    category: "category_id",
    country: "string",
    tags: "string[]",
    authorId: "user_id",
    authorName: "string",
    publishDate: "datetime",
    updatedAt: "datetime",
    readTime: "string",
    views: "number",
    status: "draft | pending | published | rejected",
    seoTitle: "string",
    metaDescription: "text",
    keywords: "string[]",
    content: "markdown_or_html",
  },
  categories: {
    id: "string primary key",
    name: "string unique",
    slug: "string unique",
  },
  tags: {
    id: "string primary key",
    name: "string unique",
    slug: "string unique",
  },
  comments: {
    id: "string primary key",
    blogId: "blog_id",
    authorName: "string",
    message: "text",
    status: "pending | approved",
    createdAt: "datetime",
  },
  drafts: {
    id: "string primary key",
    blogId: "nullable blog_id",
    authorId: "user_id",
    contentSnapshot: "json",
    updatedAt: "datetime",
  },
  views: {
    id: "string primary key",
    blogId: "blog_id",
    viewedAt: "datetime",
  },
} as const;
