import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [
        "/admin/",
        "/api/",
        "/dashboard/",
        "/login/",
        "/create-account/",
        "/forgot-password/",
        "/reset-password/",
        "/portal/student/",
        "/portal/admin/",
        "/portal/counsellor/",
        "/portal/management/",
        "/portal/forgot-password/",
        "/portal/reset-password/",
        /* Spam / hacked URLs — return 410 Gone */
        "/russianmarket/",
        "/ultimateshop/",
        "/blackbet/",
        "/courses/",
        "/key-function/",
        "/area-of-operations/",
        "/mode-of-operations/",
        "/scholarship-info/",
        "/career-roadmap/",
        "/author/",
        "/ar/",
        "/bn/",
        "/hi/",
        "/wp-admin/",
        "/wp-login/",
        "/wp-login.php",
        "/xmlrpc.php",
        "/administrator/",
        "/admin/login/",
        "/user/login/",
        "/casino/",
        "/gambling/",
        "/betting/",
        "/adult/",
        "/porn/",
        "/escort/",
      ],
    },
    sitemap: "https://www.ilmalink.com/sitemap.xml",
    host: "https://www.ilmalink.com",
  };
}
